// This file was generated by liblab | https://liblab.com/

import { Nuku } from 'nuku';

(async () => {
  const nuku = new Nuku({
    token: 'YOUR_TOKEN',
  });

  const { data } = await nuku.breeds.getBreeds();

  console.log(data);
})();
