storage:
  dbPath: /data/db
auditLog:
  destination: file
  format: JSON
  format: BSON
  path: /var/log/mongodb/audit.json
  filter: '{ atype: { $in: ["authCheck", "authenticate"] } }'
  filter: '{ atype: { $in: [ "authCheck", "createCollection", "dropDatabase" ] } }'