# host = "127.0.0.1"
# port = 27017
# username = "myBackupUser"
# password = "mySecurePassword"
# authenticationDatabase = "admin"
uri: ${MONGODB_URI_REMOTE}
archive: "./source.gz"
gzip: true
drop: true
