// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { BreedsService } from './services/breeds';
import { FactsService } from './services/facts';
import { GroupsService } from './services/groups';

export * from './services/breeds';
export * from './services/facts';
export * from './services/groups';

export * from './http';
export { Environment } from './http/environment';

export class Nuku {
  public readonly breeds: BreedsService;

  public readonly facts: FactsService;

  public readonly groups: GroupsService;

  constructor(public config: SdkConfig) {
    this.breeds = new BreedsService(this.config);

    this.facts = new FactsService(this.config);

    this.groups = new GroupsService(this.config);
  }

  set baseUrl(baseUrl: string) {
    this.breeds.baseUrl = baseUrl;
    this.facts.baseUrl = baseUrl;
    this.groups.baseUrl = baseUrl;
  }

  set environment(environment: Environment) {
    this.breeds.baseUrl = environment;
    this.facts.baseUrl = environment;
    this.groups.baseUrl = environment;
  }

  set timeoutMs(timeoutMs: number) {
    this.breeds.timeoutMs = timeoutMs;
    this.facts.timeoutMs = timeoutMs;
    this.groups.timeoutMs = timeoutMs;
  }

  set token(token: string) {
    this.breeds.token = token;
    this.facts.token = token;
    this.groups.token = token;
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
