; Generated by scriptc (LLVM backend) from /home/chrisaugu/projects/personal/nuku/nuku-api/hello.ts. Do not edit.

%ScrStr = type { i64, i64, i64 }
%ScrLogArg = type { i32, i64 }
%ScrVt = type { i64, i64, ptr }
%ScrUnion = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrClosure = type { i64, ptr, i64, ptr }
%ScrRegex = type { i64, ptr, ptr, ptr }
%ScrArr = type { i64, i64, i64, i32, ptr, ptr, ptr, ptr }
%ScrError = type { i64, ptr, ptr, ptr, ptr }
%ScrClassObj = type { i64, i64, i64, ptr, ptr }
%ScrEmitter = type { i64, ptr, ptr, ptr }
%ScrStream = type { i64, ptr, ptr, ptr, ptr }
%ScrCaught = type { i64, i32, double, i8, ptr, ptr, ptr, ptr }
%ScrBytes = type { i64, i64, i32, ptr, ptr }
%ScrBox = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrJsonBuf = type { ptr, i64, i64, ptr, i64, i64 }
%ScrDynPath = type { ptr, ptr, i64 }
%ScrIslandModule = type { ptr, ptr, i64, i64, i32, ptr, i64, i64 }
%ScrIslandEdge = type { ptr, ptr, ptr, i32 }

@scr_error_vts = external global [5 x %ScrVt]
declare void @scr_init()
declare void @scr_lib_init(i32, ptr)
declare ptr @scr_jsval_retain_v(ptr)
declare void @scr_jsval_release_v(ptr)
declare ptr @scr_str_retain_v(ptr)
declare void @scr_str_release_v(ptr)
declare ptr @scr_jsval_from_str(ptr)
declare ptr @scr_jsval_call_method(ptr, ptr, i32, ptr)
declare zeroext i1 @scr_exc_pending()
declare void @scr_str_release(ptr)
declare ptr @scr_jsval_exit_str(ptr)
declare ptr @scr_jsval_import(ptr, ptr, ptr)
declare ptr @scr_process_argv()
declare double @scr_arr_len(ptr)
declare ptr @scr_arr_get_ref(ptr, double)
declare void @scr_arr_release(ptr)
declare ptr @scr_str_concat(ptr, ptr)
declare void @scr_console_log(i64, ptr)
declare void @scr_island_modules(ptr, i64, ptr, i64)
declare i32 @scr_island_exit_code()
declare void @scr_island_set_inflate(ptr)
declare zeroext i1 @scr_zlib_inflate_exact(ptr, i64, ptr, i64)
declare zeroext i1 @scr_loop_run(ptr)
declare zeroext i1 @scr_report_unhandled_rejections()
declare void @scr_discard_unhandled_rejections()

@sc_lit_0 = internal global { i64, i64, i64, [6 x i8] } { i64 -1, i64 5, i64 5, [6 x i8] c"green\00" }
@sc_lit_1 = internal global { i64, i64, i64, [5 x i8] } { i64 -1, i64 4, i64 4, [5 x i8] c"bold\00" }
@sc_lit_2 = internal global { i64, i64, i64, [86 x i8] } { i64 -1, i64 85, i64 85, [86 x i8] c"/home/chrisaugu/projects/personal/nuku/nuku-api/node_modules/picocolors/picocolors.js\00" }
@sc_lit_3 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"default\00" }
@sc_lit_4 = internal global { i64, i64, i64, [11 x i8] } { i64 -1, i64 10, i64 10, [11 x i8] c"picocolors\00" }
@sc_lit_5 = internal global { i64, i64, i64, [6 x i8] } { i64 -1, i64 5, i64 5, [6 x i8] c"world\00" }
@sc_lit_6 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"hello, \00" }

@sc_npm_key_0 = internal constant [86 x i8] c"/home/chrisaugu/projects/personal/nuku/nuku-api/node_modules/picocolors/picocolors.js\00"
@sc_npm_src_0 = internal constant [788 x i8] c"\85\95Qk\A3@\14\85\9F\F5W\DC\F8\10\94Xi\A2m\DA\80-4t\97\85\ED\06\D2\C2R\BA\CBbtb\A4\93Q\C6\B1ii\B2\BF}\19\1D\93IF\DD\A7\A8\F7;w\EE=90\181\C8\C0\87\8C\A6!\CAs\D8n\E1sgC@\E37\FE\D5)\1F\B6[x\F9m\03\22\D57\FE[r:F\0C\92|\9A\E2\94>\16Y\96R\86\22\F0u\ADg\F6z\88\BC9?f\7F\A6\B3\EF\B39\C7y''!!.\22\94\9B\C6\D9\19I\CFB\AE4,\0B\FA}]\13\9A/\B3\F9\F4\BEC&4\BC\969\19\0E\D82\A5k\F0}\1F\8CMB\DC\91\C1+\A6\9999\8B\D2\82U\93ZN\92?==C\BF\CF\B7p\9E\EE\E7\0F\D0\E3\92\A8X/\AAf\D5\E9\D3o\96^\AE\C5\BB\06\8C!\0A>\98i\86\88\0D!Nsd\03E\19\0EB\04>\F0\CF\16\F87\BA\96\90\AC`\E0\DF\C0\A7\AEi\5C\9E3\9A\90\18|0\0C\18@Y\B6!!\11z\07_\14\9D\F2u\B64E_\DE\CD\C1\88\C4le\E9\9AF\11+(\81\BF\95\E8\B6,\C3\A0>}\CA5f\D5\E8t2q\90\05\83\AA\00\93Z,\A6\12\DFumW\ED*\F7\E4\EB\FE\A7m\B5f%\CC\0B\CC\CA-m\08\0B\9A\A7\DC\AEs]\8B\D2\D2\09Q\1F\ECW\CE\8BE\F5dV\B44\AA8E\D7\B4}\A3ju1\AD\B0F\D7\B4n\1B+\B5\A5k;\D8\AC\12\8C\C0\AC,\B4\F4\DA\D2z\AA\B6\A1,]\F8\12R\140T\C6;\E7\BE \12,0O\B8\12z\D9\94%\F8P\93\B7R\8E&`\96\D8cy\D6~\1A\EE\D3i\BBI\DD\C0\AELDl\02K\D3\F8\F5>\5C\BC\9C\AF\0D\1B\F6\8F\16'\16)\8E\0E\C0\F0\00\8CFG\CFu\B9\14E\C9\FA\A0\19ukFB\93\B0\00'\E1A\E6J\A8+\98\82D\88\E2\84\A0\03\E6I\98W\B7\22o\88\E6\124\96\A0\B1\80VI\14!r`\AE$\E6J0\FC\AF{ElE\D3\22^\1D\D0k\09\BD.Qn\14\0E\C2Wi|\C9K\F7Z\F4\A3H\F2\D2\1D6\101E\F2P\EE\A8\81\F9@\18\A7\1B\09r\1B\A0\05.$\03\5C\AF\01Y\071\22,\90\A8\8B\06*\FC\08\E4\81.\1B\90\CD*a\F2a\E3\C6\C5\82\0F\C9A\D5\1D>s|wl\A2'a\DE~\B3x.\DB\E8\0D\1B\99\AF\C7Fz\A3F\EA\F9\C4J\CFm\C4\EE\8E\CC\F4\BCF\E8\E1\D4N\EF\A2\91\9B\1E\19\EA]6B?\8F-\F5\C6\0AUG\EE\8E&\F1\8AuZ[\06O\E1Z\E3\A7\90\ED!T\D0\B6(*`G \15\B6-\96\0A\D8\1AN\85\1Cw\E4\EF\14\1E\9E\B7\C6PE;\D2\A8\C2]\A1T\E9\F6l\AAlgDU\BC=\A9*\DB\11X\15Vs\AB\ED\F8\15\B8N\A3\02#\07\BD\F3K\89_\80\F2}hZ'u\E7\E4\B6\94_\F5\7F\00"
@sc_npm_esm_0 = internal constant [291 x i8] c"const m=globalThis.__scr_require(\22/home/chrisaugu/projects/personal/nuku/nuku-api/node_modules/picocolors/picocolors.js\22);\0Aexport default m;\0Aconst H=Object.prototype.hasOwnProperty;\0Alet e0;if(H.call(m,\22createColors\22))e0=m[\22createColors\22];\0Aexport{m as \22module.exports\22,e0 as \22createColors\22};\00"
@sc_npm_modules = internal constant [1 x %ScrIslandModule] [ %ScrIslandModule { ptr @sc_npm_key_0, ptr @sc_npm_src_0, i64 787, i64 2663, i32 1, ptr @sc_npm_esm_0, i64 290, i64 0 } ]

@sc_g_e_who = internal global ptr null ; who
@sc_g_npm_1 = internal global ptr null ; pc
@sc_g_e__x25_loaded = internal global i1 false ; %loaded

define internal ptr @sc_f_banner(ptr %p_sc_l_text_0) #0 { ; banner
entry:
  %sc_l_text_0 = alloca ptr ; text
  %s7 = alloca [1 x ptr]
  %s16 = alloca [1 x ptr]
  store ptr %p_sc_l_text_0, ptr %sc_l_text_0
  %t0 = load ptr, ptr @sc_g_npm_1
  %t1 = call ptr @scr_jsval_retain_v(ptr %t0)
  %t2 = load ptr, ptr @sc_g_npm_1
  %t3 = call ptr @scr_jsval_retain_v(ptr %t2)
  %t4 = load ptr, ptr %sc_l_text_0
  %t5 = call ptr @scr_str_retain_v(ptr %t4)
  %t6 = call ptr @scr_jsval_from_str(ptr %t5)
  %t8 = getelementptr inbounds [1 x ptr], ptr %s7, i64 0, i64 0
  store ptr %t6, ptr %t8
  %t9 = call ptr @scr_jsval_call_method(ptr %t3, ptr @sc_lit_0, i32 1, ptr %s7)
  %t10 = call zeroext i1 @scr_exc_pending()
  br i1 %t10, label %exc.u0, label %exc.k1
exc.u0:
  call void @scr_jsval_release_v(ptr %t1)
  call void @scr_jsval_release_v(ptr %t3)
  call void @scr_str_release(ptr %t5)
  call void @scr_jsval_release_v(ptr %t6)
  call void @scr_jsval_release_v(ptr %t9)
  %t11 = load ptr, ptr %sc_l_text_0
  call void @scr_str_release(ptr %t11)
  ret ptr null
exc.k1:
  %t12 = call ptr @scr_jsval_exit_str(ptr %t9)
  %t13 = call zeroext i1 @scr_exc_pending()
  br i1 %t13, label %exc.u2, label %exc.k3
exc.u2:
  call void @scr_jsval_release_v(ptr %t1)
  call void @scr_jsval_release_v(ptr %t3)
  call void @scr_str_release(ptr %t5)
  call void @scr_jsval_release_v(ptr %t6)
  call void @scr_jsval_release_v(ptr %t9)
  call void @scr_str_release(ptr %t12)
  %t14 = load ptr, ptr %sc_l_text_0
  call void @scr_str_release(ptr %t14)
  ret ptr null
exc.k3:
  %t15 = call ptr @scr_jsval_from_str(ptr %t12)
  %t17 = getelementptr inbounds [1 x ptr], ptr %s16, i64 0, i64 0
  store ptr %t15, ptr %t17
  %t18 = call ptr @scr_jsval_call_method(ptr %t1, ptr @sc_lit_1, i32 1, ptr %s16)
  %t19 = call zeroext i1 @scr_exc_pending()
  br i1 %t19, label %exc.u4, label %exc.k5
exc.u4:
  call void @scr_jsval_release_v(ptr %t1)
  call void @scr_jsval_release_v(ptr %t3)
  call void @scr_str_release(ptr %t5)
  call void @scr_jsval_release_v(ptr %t6)
  call void @scr_jsval_release_v(ptr %t9)
  call void @scr_str_release(ptr %t12)
  call void @scr_jsval_release_v(ptr %t15)
  call void @scr_jsval_release_v(ptr %t18)
  %t20 = load ptr, ptr %sc_l_text_0
  call void @scr_str_release(ptr %t20)
  ret ptr null
exc.k5:
  %t21 = call ptr @scr_jsval_exit_str(ptr %t18)
  %t22 = call zeroext i1 @scr_exc_pending()
  br i1 %t22, label %exc.u6, label %exc.k7
exc.u6:
  call void @scr_jsval_release_v(ptr %t1)
  call void @scr_jsval_release_v(ptr %t3)
  call void @scr_str_release(ptr %t5)
  call void @scr_jsval_release_v(ptr %t6)
  call void @scr_jsval_release_v(ptr %t9)
  call void @scr_str_release(ptr %t12)
  call void @scr_jsval_release_v(ptr %t15)
  call void @scr_jsval_release_v(ptr %t18)
  call void @scr_str_release(ptr %t21)
  %t23 = load ptr, ptr %sc_l_text_0
  call void @scr_str_release(ptr %t23)
  ret ptr null
exc.k7:
  call void @scr_jsval_release_v(ptr %t1)
  call void @scr_jsval_release_v(ptr %t3)
  call void @scr_str_release(ptr %t5)
  call void @scr_jsval_release_v(ptr %t6)
  call void @scr_jsval_release_v(ptr %t9)
  call void @scr_str_release(ptr %t12)
  call void @scr_jsval_release_v(ptr %t15)
  call void @scr_jsval_release_v(ptr %t18)
  %t24 = load ptr, ptr %sc_l_text_0
  call void @scr_str_release(ptr %t24)
  ret ptr %t21
}

define internal void @sc_f__x25_init_0() #0 { ; %init.0
entry:
  %s10 = alloca ptr
  %logargs = alloca [1 x %ScrLogArg]
  %t0 = load i1, ptr @sc_g_e__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_e__x25_loaded
  %t1 = call ptr @scr_str_retain_v(ptr @sc_lit_2)
  %t2 = call ptr @scr_str_retain_v(ptr @sc_lit_3)
  %t3 = call ptr @scr_str_retain_v(ptr @sc_lit_4)
  %t4 = call ptr @scr_jsval_import(ptr %t1, ptr %t2, ptr %t3)
  %t5 = call zeroext i1 @scr_exc_pending()
  br i1 %t5, label %exc.u2, label %exc.k3
exc.u2:
  call void @scr_str_release(ptr %t1)
  call void @scr_str_release(ptr %t2)
  call void @scr_str_release(ptr %t3)
  call void @scr_jsval_release_v(ptr %t4)
  ret void
exc.k3:
  %t6 = load ptr, ptr @sc_g_npm_1
  call void @scr_jsval_release_v(ptr %t6)
  store ptr %t4, ptr @sc_g_npm_1
  call void @scr_str_release(ptr %t1)
  call void @scr_str_release(ptr %t2)
  call void @scr_str_release(ptr %t3)
  %t7 = call ptr @scr_process_argv()
  %t8 = call double @scr_arr_len(ptr %t7)
  %t9 = fcmp ogt double %t8, 0x4000000000000000
  br i1 %t9, label %tern.t4, label %tern.f5
tern.t4:
  %t11 = call ptr @scr_process_argv()
  %t12 = call ptr @scr_arr_get_ref(ptr %t11, double 0x4000000000000000)
  store ptr %t12, ptr %s10
  call void @scr_arr_release(ptr %t11)
  br label %tern.j6
tern.f5:
  %t13 = call ptr @scr_str_retain_v(ptr @sc_lit_5)
  store ptr %t13, ptr %s10
  br label %tern.j6
tern.j6:
  %t14 = load ptr, ptr %s10
  %t15 = load ptr, ptr @sc_g_e_who
  call void @scr_str_release(ptr %t15)
  store ptr %t14, ptr @sc_g_e_who
  call void @scr_arr_release(ptr %t7)
  %t16 = call ptr @scr_str_retain_v(ptr @sc_lit_6)
  %t17 = load ptr, ptr @sc_g_e_who
  %t18 = call ptr @scr_str_retain_v(ptr %t17)
  %t19 = call ptr @scr_str_concat(ptr %t16, ptr %t18)
  %t20 = call ptr @sc_f_banner(ptr %t19)
  %t21 = call zeroext i1 @scr_exc_pending()
  br i1 %t21, label %exc.u7, label %exc.k8
exc.u7:
  call void @scr_str_release(ptr %t16)
  call void @scr_str_release(ptr %t18)
  call void @scr_str_release(ptr %t20)
  ret void
exc.k8:
  %t22 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t22
  %t23 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t20, ptr %t23
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t16)
  call void @scr_str_release(ptr %t18)
  call void @scr_str_release(ptr %t20)
  ret void
}

define internal void @sc_f__x25_main() #0 { ; %main
entry:
  call void @sc_f__x25_init_0()
  %t0 = call zeroext i1 @scr_exc_pending()
  br i1 %t0, label %exc.u0, label %exc.k1
exc.u0:
  ret void
exc.k1:
  ret void
}

declare void @scr_exc_print_uncaught()

define i32 @main(i32 %argc, ptr %argv) #0 {
entry:
  call void @scr_init()
  store i64 0, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 1) ; Error
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 0)
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 1) ; TypeError
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 0)
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 1) ; RangeError
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 0)
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 1) ; SyntaxError
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 1) ; DOMException
  call void @scr_lib_init(i32 %argc, ptr %argv)
  call void @scr_island_set_inflate(ptr @scr_zlib_inflate_exact)
  call void @scr_island_modules(ptr @sc_npm_modules, i64 1, ptr null, i64 0)
  call void @sc_f__x25_main()
  %exc = call zeroext i1 @scr_exc_pending()
  br i1 %exc, label %uncaught, label %ok
uncaught:
  call void @scr_exc_print_uncaught()
  %gu0 = load ptr, ptr @sc_g_e_who
  call void @scr_str_release(ptr %gu0) ; who
  %gu1 = load ptr, ptr @sc_g_npm_1
  call void @scr_jsval_release_v(ptr %gu1) ; pc
  ret i32 1
ok:
  %loop_rejection = call zeroext i1 @scr_loop_run(ptr null)
  %lexc = call zeroext i1 @scr_exc_pending()
  br i1 %lexc, label %luncaught, label %lok
luncaught:
  call void @scr_exc_print_uncaught()
  %gl0 = load ptr, ptr @sc_g_e_who
  call void @scr_str_release(ptr %gl0) ; who
  %gl1 = load ptr, ptr @sc_g_npm_1
  call void @scr_jsval_release_v(ptr %gl1) ; pc
  ret i32 1
lok:
  br i1 %loop_rejection, label %lreported, label %lclean
lreported:
  call void @scr_discard_unhandled_rejections()
  %gq0 = load ptr, ptr @sc_g_e_who
  call void @scr_str_release(ptr %gq0) ; who
  %gq1 = load ptr, ptr @sc_g_npm_1
  call void @scr_jsval_release_v(ptr %gq1) ; pc
  ret i32 1
lclean:
  %rej = call zeroext i1 @scr_report_unhandled_rejections()
  br i1 %rej, label %lrej, label %lrok
lrej:
  %gr0 = load ptr, ptr @sc_g_e_who
  call void @scr_str_release(ptr %gr0) ; who
  %gr1 = load ptr, ptr @sc_g_npm_1
  call void @scr_jsval_release_v(ptr %gr1) ; pc
  ret i32 1
lrok:
  %g0 = load ptr, ptr @sc_g_e_who
  call void @scr_str_release(ptr %g0) ; who
  %g1 = load ptr, ptr @sc_g_npm_1
  call void @scr_jsval_release_v(ptr %g1) ; pc
  %island_exit = call i32 @scr_island_exit_code()
  ret i32 %island_exit
}

attributes #0 = { sanitize_address }
