block-beta
columns 1
  block:ID
    X["REST"]
    Y["SSE"]
    Z["WebSocket | MCP | GraphQL | gRPC"]
  end
  block:T
    C["ExpressJS"]
    D["GraphQL"]
    E["MCP"]
    G["SSE"]
    H["WebSocket"]
  end
  B["HTTP"]
  A["Node JS"]